In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
a = np.array([0,0,0,0,0,0,0,0,0,0])
b = np.full_like(a,1)
c = np.full((5),100)
a = b.copy()
c

array([100, 100, 100, 100, 100])

In [3]:
a = np.array([1,2,3,4,5,6])
b = b.reshape(2,5)
a =a.reshape(3,2)

z = np.random.rand(3,4)
z=z*10
z.astype(np.int32)
b


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
z = z*10
value, count = np.unique(z, return_counts=True)
index = np.argmax(count)
max = value[index]
max

np.float64(14.935517121126352)

In [ ]:
a = np.arange(0,36)
a = a.reshape(6,6)
a[0,:] = 1
a[:,0] = 1
a[-1,:] = 1
a[:,-1] = 1
a

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [53]:
a = np.arange(0,36)
a = a.reshape(6,6)
a[::-1,::-1]
a = np.random.uniform(0,1, size=(1000))
np.var(a)

np.float64(0.08367376976412899)

In [19]:
a = np.random.randint(0,50, size=(10))
a[a%3 ==0] = -1
print(a)
a[np.isnan(a)]= np.nanmean(a)

[14 -1 32 -1 10 -1 -1 -1 -1  2]


In [31]:
a = np.random.randint(0,100, size=(5,5))
col = a.mean(axis=0)
a-col

array([[ 35.4, -12.8,  33.4,  11. , -21.2],
       [-26.6,  47.2, -47.6, -27. , -16.2],
       [ 11.4, -35.8,   0.4,  30. ,  39.8],
       [ -8.6,  41.2,  28.4,  -5. ,  14.8],
       [-11.6, -39.8, -14.6,  -9. , -17.2]])

In [35]:
a = np.arange(1,6)
b = np.arange(4,9)
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]


In [45]:
a = np.arange(1,37)
a = a.reshape(6,6)
print(np.linalg.det(a))
print(np.linalg.matrix_rank(a))
print(np.linalg.eig(a))
print(a[::-1,::-1])

0.0
2
EigResult(eigenvalues=array([ 1.16411822e+02+0.00000000e+00j, -5.41182151e+00+0.00000000e+00j,
       -1.29522752e-15+3.03403945e-15j, -1.29522752e-15-3.03403945e-15j,
       -3.36522484e-15+0.00000000e+00j,  1.73182808e-15+0.00000000e+00j]), eigenvectors=array([[-0.08190341+0.j        ,  0.63110943+0.j        ,
        -0.22481244+0.23752107j, -0.22481244-0.23752107j,
         0.32514027+0.j        ,  0.02966602+0.j        ],
       [-0.19353989+0.j        ,  0.39298443+0.j        ,
         0.68634984+0.j        ,  0.68634984-0.j        ,
        -0.62687855+0.j        ,  0.28386664+0.j        ],
       [-0.30517638+0.j        ,  0.15485944+0.j        ,
        -0.35278768-0.40954769j, -0.35278768+0.40954769j,
         0.56403408+0.j        , -0.45282174+0.j        ],
       [-0.41681286+0.j        , -0.08326555+0.j        ,
        -0.2747546 -0.03214635j, -0.2747546 +0.03214635j,
        -0.40243915+0.j        , -0.32864799+0.j        ],
       [-0.52844934+0.j        , -0.32